
package visao;

import java.awt.Color;
import javax.swing.JOptionPane;

public class TelaPrincipal extends javax.swing.JFrame {

    public TelaPrincipal() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menCad = new javax.swing.JMenu();
        menCadMoto = new javax.swing.JMenuItem();
        menCadUser = new javax.swing.JMenuItem();
        menCadCli = new javax.swing.JMenuItem();
        menLis = new javax.swing.JMenu();
        menLisMoto = new javax.swing.JMenuItem();
        menLisUsuario = new javax.swing.JMenuItem();
        menLisCliente = new javax.swing.JMenuItem();
        menRel = new javax.swing.JMenu();
        menRelMensal = new javax.swing.JMenuItem();
        menAju = new javax.swing.JMenu();
        menSobre = new javax.swing.JMenuItem();
        menOpc = new javax.swing.JMenu();
        menSair = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SISTEMA DE CADASTRO");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        Desktop.setForeground(new java.awt.Color(255, 255, 255));
        Desktop.setMaximumSize(new java.awt.Dimension(700, 540));
        Desktop.setPreferredSize(new java.awt.Dimension(720, 540));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        getContentPane().add(Desktop);
        Desktop.setBounds(0, 0, 720, 580);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/aaaaaaaaaaaaaaaaaa.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(730, 390, 180, 180);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sportsprologo.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(730, 0, 180, 190);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sobre2.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(710, 220, 200, 90);

        menCad.setText("Cadastrar");

        menCadMoto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menCadMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadIconMotos.png"))); // NOI18N
        menCadMoto.setText("Cadastro de Motos");
        menCadMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadMotoActionPerformed(evt);
            }
        });
        menCad.add(menCadMoto);

        menCadUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        menCadUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadUser.png"))); // NOI18N
        menCadUser.setText("Cadastro de Usuários");
        menCadUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadUserActionPerformed(evt);
            }
        });
        menCad.add(menCadUser);

        menCadCli.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menCadCli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadCli.png"))); // NOI18N
        menCadCli.setText("Cadastro de Clientes");
        menCadCli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menCadCliActionPerformed(evt);
            }
        });
        menCad.add(menCadCli);

        Menu.add(menCad);

        menLis.setText("Listar");

        menLisMoto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        menLisMoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadIconMotos.png"))); // NOI18N
        menLisMoto.setText("Listar Motos");
        menLisMoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menLisMotoActionPerformed(evt);
            }
        });
        menLis.add(menLisMoto);

        menLisUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        menLisUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadUser.png"))); // NOI18N
        menLisUsuario.setText("Listar Usuários");
        menLisUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menLisUsuarioActionPerformed(evt);
            }
        });
        menLis.add(menLisUsuario);

        menLisCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        menLisCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadCli.png"))); // NOI18N
        menLisCliente.setText("Listar Clientes");
        menLisCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menLisClienteActionPerformed(evt);
            }
        });
        menLis.add(menLisCliente);

        Menu.add(menLis);

        menRel.setText("Relatório");

        menRelMensal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        menRelMensal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/IconeRel.png"))); // NOI18N
        menRelMensal.setText("Relatório Mensal");
        menRel.add(menRelMensal);

        Menu.add(menRel);

        menAju.setText("Ajuda");

        menSobre.setText("Sobre");
        menSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSobreActionPerformed(evt);
            }
        });
        menAju.add(menSobre);

        Menu.add(menAju);

        menOpc.setText("Opções");

        menSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Sair.png"))); // NOI18N
        menSair.setText("Sair");
        menSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menSairActionPerformed(evt);
            }
        });
        menOpc.add(menSair);

        Menu.add(menOpc);

        setJMenuBar(Menu);

        setSize(new java.awt.Dimension(954, 626));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSobreActionPerformed
        // Chamando a Tela Sobre:
        TelaAjuda ajuda = new TelaAjuda();
        ajuda.setVisible(true);


    }//GEN-LAST:event_menSobreActionPerformed

    private void menSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menSairActionPerformed
        // Aqui será exibido uma caixa de diálogo
        //Criar uma variável do tipo inteiro
        int sair = JOptionPane.showConfirmDialog(null, "Deseja encerrar a sessão?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);

        }
    }//GEN-LAST:event_menSairActionPerformed

    private void menCadCliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadCliActionPerformed
        new CadastrarClientes().setVisible(true);
    }//GEN-LAST:event_menCadCliActionPerformed

    private void menCadMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadMotoActionPerformed
        new CadastrarMotos().setVisible(true);
    }//GEN-LAST:event_menCadMotoActionPerformed

    private void menCadUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menCadUserActionPerformed
        new CadastrarUsuario().setVisible(true);
    }//GEN-LAST:event_menCadUserActionPerformed

    private void menLisMotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menLisMotoActionPerformed
        new ListarMotos().setVisible(true);
    }//GEN-LAST:event_menLisMotoActionPerformed

    private void menLisUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menLisUsuarioActionPerformed
        new ListarUsuario().setVisible(true);
    }//GEN-LAST:event_menLisUsuarioActionPerformed

    private void menLisClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menLisClienteActionPerformed
        new ListarClientes().setVisible(true);
    }//GEN-LAST:event_menLisClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu menAju;
    private javax.swing.JMenu menCad;
    private javax.swing.JMenuItem menCadCli;
    private javax.swing.JMenuItem menCadMoto;
    private javax.swing.JMenuItem menCadUser;
    private javax.swing.JMenu menLis;
    private javax.swing.JMenuItem menLisCliente;
    private javax.swing.JMenuItem menLisMoto;
    private javax.swing.JMenuItem menLisUsuario;
    private javax.swing.JMenu menOpc;
    private javax.swing.JMenu menRel;
    private javax.swing.JMenuItem menRelMensal;
    private javax.swing.JMenuItem menSair;
    private javax.swing.JMenuItem menSobre;
    // End of variables declaration//GEN-END:variables
}
